export const AUTH = "AUTH";
export const LOCATION = "LOCATION";
export const SYSTEM_SETTINGS_STATE = "SYSTEM_SETTINGS_STATE";
export const SAVE_CART_ITEM_TO_CART = "SAVE_CART_ITEM_TO_CART";
export const CART_LOGIC_MODIFICATION_DATA = "CART_LOGIC_MODIFICATION_DATA";
export const PREVIOUS_INFORMATION = "PREVIOUS_INFORMATION";
export const UPDATE_FREIGHT_DETAILS = "UPDATE_FREIGHT_DETAILS";